# Generated by Django 6.0.6 on 2026-06-12 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System Configurations',
            },
        ),
        migrations.CreateModel(
            name='Callsign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(db_index=True, max_length=50, unique=True)),
                ('operator_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('online', 'Online'), ('standby', 'Standby'), ('busy', 'Busy'), ('emergency', 'Emergency'), ('offline', 'Offline')], db_index=True, default='offline', max_length=20)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Callsigns',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['status'], name='command_cen_status_abe099_idx'), models.Index(fields=['callsign'], name='command_cen_callsig_f47df1_idx'), models.Index(fields=['-updated_at'], name='command_cen_updated_bcc759_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('emergency', 'Emergency'), ('critical', 'Critical')], db_index=True, default='info', max_length=20)),
                ('event_type', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('callsign', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity'], name='command_cen_severit_e73179_idx'), models.Index(fields=['status'], name='command_cen_status_5ec9fc_idx'), models.Index(fields=['-timestamp'], name='command_cen_timesta_1cc39e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.CharField(db_index=True, max_length=50)),
                ('building_name', models.CharField(max_length=255)),
                ('incident_type', models.CharField(choices=[('fire', 'Fire'), ('alert', 'Alert'), ('emergency', 'Emergency'), ('test', 'Test')], default='alert', max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Incidents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['building_id'], name='command_cen_buildin_0d5df0_idx'), models.Index(fields=['status'], name='command_cen_status_7a82d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(db_index=True, max_length=50)),
                ('operator_name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('frequency', models.CharField(max_length=20)),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('confidence', models.IntegerField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('emergency', 'Emergency')], db_index=True, default='info', max_length=20)),
                ('is_emergency', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('live_mic', 'Live Microphone'), ('simulator', 'Simulator'), ('api', 'API')], default='api', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Transcripts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['callsign'], name='command_cen_callsig_fa071c_idx'), models.Index(fields=['priority'], name='command_cen_priorit_5462ea_idx'), models.Index(fields=['-timestamp'], name='command_cen_timesta_373fa0_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View')], max_length=20)),
                ('table_name', models.CharField(db_index=True, max_length=100)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['table_name'], name='command_cen_table_n_370820_idx'), models.Index(fields=['-created_at'], name='command_cen_created_714adc_idx')],
            },
        ),
    ]
